<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button tampil password</name>
   <tag></tag>
   <elementGuidId>f1455017-65db-414e-b516-a673b2366fff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_c_Yk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_c_Yk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acc7e9c9-6cd7-4316-88cb-494cb97ccb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9lsb _9ls8</value>
      <webElementGuid>11d876f1-7bf8-42d8-ad4f-e8cb618beeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_c_Yk</value>
      <webElementGuid>b9e39c66-604f-438e-b2ea-cce945ec3886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_c_Yk&quot;)</value>
      <webElementGuid>f4e7e278-dc05-4592-bcf1-1430e5e0e6f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u_0_c_Yk']</value>
      <webElementGuid>e433ad2b-7d1f-4002-bc63-2b4e1e6f9c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_b_Bm']/a/div/div</value>
      <webElementGuid>b7ae955b-0d49-4caa-9766-049c82c3b2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>35d1fab9-6872-4f5d-98e9-3debc9cefbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u_0_c_Yk']</value>
      <webElementGuid>cd863d16-6ab0-42df-886b-f24ab2b2512e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
