<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invalid username or password_u_0_c_T7</name>
   <tag></tag>
   <elementGuidId>7e087b75-d231-4a3e-90a5-a6ee3f545e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_c_T7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_c_T7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a615f4a6-d4ac-4210-9ad6-740040088050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9lsb _9ls8</value>
      <webElementGuid>0556772c-5f03-4b0b-b0ca-981bbcbc409e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_c_T7</value>
      <webElementGuid>b9683c4d-0b34-45f8-a90b-0d9d52951704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_c_T7&quot;)</value>
      <webElementGuid>153f9f74-9c1f-4958-a0ed-8a92c544d675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u_0_c_T7']</value>
      <webElementGuid>f75a9c99-0c40-4558-b3c9-5ee0c4b40127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_b_6Q']/a/div/div</value>
      <webElementGuid>63b8f5f7-16fa-4f87-828b-c6db81bb7b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>fd0d35e9-0194-46a6-bb26-8942740d0a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u_0_c_T7']</value>
      <webElementGuid>fa35ecd6-aae2-45a3-b5cc-68fe2a2614ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
